# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='bienes',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='orden',
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='bienes',
        ),
        migrations.AddField(
            model_name='orden',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='bienes.Servicio'),
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.AddField(
            model_name='detalleordenproducto',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes.Orden'),
        ),
        migrations.AddField(
            model_name='detalleordenproducto',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes.Producto'),
        ),
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(blank=True, through='bienes.DetalleOrdenProducto', to='bienes.Producto'),
        ),
    ]
